# Logging settings.
[logging]

  # Log level.
  #
  # Valid options are:
  #   * TRACE
  #   * DEBUG
  #   * INFO
  #   * WARN
  #   * ERROR
  level = "info"


# Multiplexer configuration.
[multiplexer]

  # Interface:port of UDP bind.
  #
  # This this is the interface:port on which the Multiplexer will receive
  # data from the gateways.
  bind = "0.0.0.0:1700"

  # Servers to forward gateway data to.
  #
  # Example configuration:
  # [[multiplexer.server]]

  #   # Hostname:port of the server.
  #   server="example.com:1700"

  #   # Only allow uplink.
  #   #
  #   # If set to true, any downlink will be discarded.
  #   uplink_only=false

  #   # Gateway ID prefix filters.
  #   #
  #   # If not set, data of all gateways will be forwarded. If set, only data
  #   # from gateways with a matching Gateway ID will be forwarded.
  #   #
  #   # Example:
  #   # * "0102030405060708/32": Exact match (all 32 bits of the filter must match)
  #   # * "0102030400000000/16": All gateway IDs starting with "01020304" (filter on 16 most significant bits)
  #   gateway_id_prefixes=[]
  #
  #   # Filter configuration.
  #   [multiplexer.server.filters]

  #     # DevAddr prefix filters.
  #     #
  #     # Example configuration:
  #     # dev_addr_prefixes=["0000ff00/24"]
  #     #
  #     # The above filter means that the 24MSB of 0000ff00 will be used to
  #     # filter DevAddrs. Uplinks with DevAddrs that do not match any of the
  #     # configured filters will not be forwarded. Leaving this option empty
  #     # disables filtering on DevAddr.
  #     dev_addr_prefixes=[]

  #     # JoinEUI prefix filters.
  #     #
  #     # Example configuration:
  #     # join_eui_prefixes=["0000ff0000000000/24"]
  #     #
  #     # The above filter means that the 24MSB of 0000ff0000000000 will be used
  #     # to filter JoinEUIs. Uplinks with JoinEUIs that do not match any of the
  #     # configured filters will not be forwarded. Leaving this option empty
  #     # disables filtering on JoinEUI.
  #     join_eui_prefixes=[]


# Monitoring configuration.
[monitoring]

  # Interface:port.
  #
  # If set, this will enable the monitoring endpoints. If not set, the endpoint
  # will be disabled. Endpoints:
  #
  # * /metrics: Exposes Prometheus metrics.
  bind = ""
